[package]
name = "iced_reg"
version = "0.1.0"
authors = ["Radovan Bla≈æek <blazra@gmail.com>"]
edition = "2021"
publish = false

[dependencies]
iced = { git = "https://github.com/iced-rs/iced.git", branch = "advanced-text", features = ["lazy"]}